# Generated by Django 6.0.2 on 2026-03-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
