# Generated by Django 6.0.2 on 2026-03-08 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_alter_productreview_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cutoff_time',
            field=models.TimeField(blank=True, help_text='Order cutoff time for next day delivery', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_available',
            field=models.BooleanField(default=True, help_text='Can this product be delivered?'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_days',
            field=models.JSONField(default=list, help_text='Days when delivery is available (0-6, Monday=0)'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Standard delivery fee charged to customer', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_partner_commission',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Percentage (%) paid to delivery partner', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_partner_commission_fixed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount paid to delivery partner', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_partner_required',
            field=models.BooleanField(default=True, help_text='Does this need a delivery partner?'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_zones',
            field=models.JSONField(default=list, help_text='List of delivery zones/cities'),
        ),
        migrations.AddField(
            model_name='product',
            name='estimated_delivery_days',
            field=models.IntegerField(default=2, help_text='Estimated days for delivery'),
        ),
        migrations.AddField(
            model_name='product',
            name='express_delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee for express delivery (if available)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='express_delivery_hours',
            field=models.IntegerField(blank=True, help_text='Hours for express delivery', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='farm_pickup_address',
            field=models.TextField(blank=True, help_text='Address for farm pickup'),
        ),
        migrations.AddField(
            model_name='product',
            name='farmer_delivers_self',
            field=models.BooleanField(default=False, help_text='Farmer delivers without partner'),
        ),
        migrations.AddField(
            model_name='product',
            name='farmer_delivery_radius',
            field=models.IntegerField(blank=True, help_text='Delivery radius in km', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='free_delivery_min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Order amount for free delivery', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='max_delivery_distance',
            field=models.IntegerField(blank=True, help_text='Maximum delivery distance in km', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pickup_available',
            field=models.BooleanField(default=True, help_text='Can customers pick up from farm?'),
        ),
        migrations.AddField(
            model_name='product',
            name='pickup_instructions',
            field=models.TextField(blank=True, help_text='Special instructions for pickup'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_refrigeration',
            field=models.BooleanField(default=False, help_text='Does product need cold storage?'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_special_handling',
            field=models.BooleanField(default=False, help_text='Fragile/delicate items'),
        ),
        migrations.AddField(
            model_name='product',
            name='restricted_areas',
            field=models.JSONField(default=list, help_text='Areas where delivery is NOT available'),
        ),
        migrations.AddField(
            model_name='product',
            name='special_handling_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['farmer', 'is_active'], name='products_pr_farmer__c6c20e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['delivery_available', 'pickup_available'], name='products_pr_deliver_3cfc1d_idx'),
        ),
    ]
