# Generated by Django 6.0.2 on 2026-03-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_cutoff_time_product_delivery_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_farmer__c6c20e_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_categor_50f5f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_deliver_3cfc1d_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_partner_commission',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_partner_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_zones',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='estimated_delivery_days',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='farm_pickup_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='free_delivery_min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pickup_available',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='cutoff_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery_days',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery_partner_commission_fixed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='express_delivery_fee',
        ),
        migrations.RemoveField(
            model_name='product',
            name='express_delivery_hours',
        ),
        migrations.RemoveField(
            model_name='product',
            name='farmer_delivers_self',
        ),
        migrations.RemoveField(
            model_name='product',
            name='farmer_delivery_radius',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_delivery_distance',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pickup_instructions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='requires_refrigeration',
        ),
        migrations.RemoveField(
            model_name='product',
            name='requires_special_handling',
        ),
        migrations.RemoveField(
            model_name='product',
            name='restricted_areas',
        ),
        migrations.RemoveField(
            model_name='product',
            name='special_handling_instructions',
        ),
    ]
