# Generated by Django 6.0.2 on 2026-03-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_options_alter_productreview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accepts_cod',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='accepts_online_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bank_account_details',
            field=models.JSONField(blank=True, default=dict, help_text='Bank account details for payment'),
        ),
        migrations.AddField(
            model_name='product',
            name='pickup_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='product',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID for direct payment (e.g., farmer@okhdfcbank)', max_length=100, null=True),
        ),
    ]
