# Generated by Django 6.0.2 on 2026-03-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_date', models.DateField(auto_now_add=True)),
                ('predicted_demand', models.FloatField(help_text='Predicted demand in quantity')),
                ('confidence_score', models.FloatField(default=0.5, help_text='Confidence score from 0 to 1')),
                ('seasonal_factor', models.FloatField(default=1.0, help_text='Seasonal multiplier')),
                ('festival_factor', models.FloatField(default=1.0, help_text='Festival multiplier')),
                ('historical_trend', models.FloatField(default=0, help_text='Historical trend value')),
                ('weather_factor', models.FloatField(blank=True, default=1.0, help_text='Weather impact factor', null=True)),
                ('market_trend', models.FloatField(default=1.0, help_text='Market trend factor')),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('suggested_quantity', models.FloatField(blank=True, help_text='Suggested quantity to produce', null=True)),
                ('suggested_harvest_date', models.DateField(blank=True, help_text='Optimal harvest date', null=True)),
                ('recommendation_text', models.TextField(blank=True, help_text='Human readable recommendation')),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('actual_demand', models.FloatField(blank=True, help_text='Actual demand for accuracy tracking', null=True)),
                ('prediction_accuracy', models.FloatField(blank=True, help_text='Accuracy of prediction', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-insight_date'],
            },
        ),
        migrations.CreateModel(
            name='FestivalCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ta', models.CharField(blank=True, help_text='Tamil name', max_length=100)),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='If festival spans multiple days', null=True)),
                ('region', models.CharField(blank=True, help_text='Blank means all regions', max_length=100)),
                ('impact_days_before', models.IntegerField(default=7, help_text='Days before festival when demand starts')),
                ('impact_days_after', models.IntegerField(default=3, help_text='Days after festival when demand continues')),
                ('demand_multiplier', models.FloatField(default=1.5, help_text='Expected demand multiplier')),
                ('is_recurring', models.BooleanField(default=False, help_text='If festival occurs every year')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_sold', models.FloatField()),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('day_of_week', models.IntegerField(help_text='0-6, Monday is 0')),
                ('week_of_year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('is_weekend', models.BooleanField(default=False)),
                ('is_festival', models.BooleanField(default=False)),
                ('festival_name', models.CharField(blank=True, max_length=100)),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in Celsius', null=True)),
                ('rainfall', models.FloatField(blank=True, help_text='Rainfall in mm', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Humidity percentage', null=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('DEMAND_PREDICTION', 'Demand Prediction'), ('PRICE_OPTIMIZATION', 'Price Optimization'), ('CROP_SUGGESTION', 'Crop Suggestion')], max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('TRAINING', 'Training'), ('ACTIVE', 'Active'), ('DEPRECATED', 'Deprecated'), ('FAILED', 'Failed')], default='TRAINING', max_length=20)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, help_text='Mean Absolute Error', null=True)),
                ('rmse', models.FloatField(blank=True, help_text='Root Mean Square Error', null=True)),
                ('training_start', models.DateTimeField(blank=True, null=True)),
                ('training_end', models.DateTimeField(blank=True, null=True)),
                ('training_data_start', models.DateField(blank=True, null=True)),
                ('training_data_end', models.DateField(blank=True, null=True)),
                ('training_samples', models.IntegerField(default=0)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='ml_models/')),
                ('model_config', models.JSONField(default=dict, help_text='Model hyperparameters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(help_text='Features used for prediction')),
                ('predicted_value', models.FloatField()),
                ('confidence', models.FloatField()),
                ('actual_value', models.FloatField(blank=True, help_text='For tracking accuracy', null=True)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('processing_time_ms', models.IntegerField(help_text='Time taken for prediction')),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='RegionalDemandPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('jan_demand', models.FloatField(default=1.0)),
                ('feb_demand', models.FloatField(default=1.0)),
                ('mar_demand', models.FloatField(default=1.0)),
                ('apr_demand', models.FloatField(default=1.0)),
                ('may_demand', models.FloatField(default=1.0)),
                ('jun_demand', models.FloatField(default=1.0)),
                ('jul_demand', models.FloatField(default=1.0)),
                ('aug_demand', models.FloatField(default=1.0)),
                ('sep_demand', models.FloatField(default=1.0)),
                ('oct_demand', models.FloatField(default=1.0)),
                ('nov_demand', models.FloatField(default=1.0)),
                ('dec_demand', models.FloatField(default=1.0)),
                ('base_daily_demand', models.FloatField(default=100.0, help_text='Average daily demand in kg')),
                ('price_elasticity', models.FloatField(default=-0.5, help_text='How demand changes with price')),
                ('population', models.IntegerField(blank=True, help_text='Regional population', null=True)),
                ('income_level', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['region', 'category'],
            },
        ),
    ]
