# Generated by Django 6.0.2 on 2026-03-01 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demandinsight',
            name='farmer',
            field=models.ForeignKey(limit_choices_to={'role': 'FARMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='demand_insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandinsight',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_insights', to='products.category'),
        ),
        migrations.AddField(
            model_name='festivalcalendar',
            name='affected_categories',
            field=models.ManyToManyField(blank=True, related_name='festivals', to='products.category'),
        ),
        migrations.AddField(
            model_name='festivalcalendar',
            name='affected_products',
            field=models.ManyToManyField(blank=True, related_name='festivals', to='products.product'),
        ),
        migrations.AddField(
            model_name='historicalsalesdata',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_sales', to='products.product'),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='analytics.mlmodel'),
        ),
        migrations.AddField(
            model_name='regionaldemandpattern',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_patterns', to='products.category'),
        ),
        migrations.AddIndex(
            model_name='demandinsight',
            index=models.Index(fields=['farmer', 'insight_date'], name='analytics_d_farmer__c3aa61_idx'),
        ),
        migrations.AddIndex(
            model_name='demandinsight',
            index=models.Index(fields=['product_category', 'insight_date'], name='analytics_d_product_0fa671_idx'),
        ),
        migrations.AddIndex(
            model_name='festivalcalendar',
            index=models.Index(fields=['date'], name='analytics_f_date_81dd3b_idx'),
        ),
        migrations.AddIndex(
            model_name='festivalcalendar',
            index=models.Index(fields=['region', 'date'], name='analytics_f_region_592011_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalsalesdata',
            index=models.Index(fields=['product', 'date'], name='analytics_h_product_8007f7_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalsalesdata',
            index=models.Index(fields=['region', 'date'], name='analytics_h_region_dfd68c_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalsalesdata',
            index=models.Index(fields=['product', 'month', 'year'], name='analytics_h_product_5303f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='historicalsalesdata',
            unique_together={('product', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='mlmodel',
            unique_together={('model_type', 'version')},
        ),
        migrations.AddIndex(
            model_name='predictionlog',
            index=models.Index(fields=['model', 'prediction_date'], name='analytics_p_model_i_406cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionlog',
            index=models.Index(fields=['farmer', 'prediction_date'], name='analytics_p_farmer__fdab9c_idx'),
        ),
        migrations.AddIndex(
            model_name='regionaldemandpattern',
            index=models.Index(fields=['region', 'category'], name='analytics_r_region_1589e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='regionaldemandpattern',
            unique_together={('region', 'category')},
        ),
    ]
