version: '3.9'

services:
  backend:
    build: ./backend
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 core.wsgi:application"

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: uzhavar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: