# Generated by Django 6.0.2 on 2026-03-01 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ta', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('content_ta', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('target_roles', models.JSONField(default=list, help_text="['FARMER', 'CUSTOMER', 'DELIVERY']")),
                ('is_public', models.BooleanField(default=True)),
                ('publish_from', models.DateTimeField()),
                ('publish_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publish_from', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VERIFY', 'Verify'), ('REJECT', 'Reject'), ('BAN', 'Ban'), ('UNBAN', 'Unban'), ('OTHER', 'Other')], max_length=20)),
                ('content_type', models.CharField(help_text='Model name', max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('changes', models.JSONField(default=dict, help_text='Changes made')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('dispute_type', models.CharField(choices=[('ORDER_ISSUE', 'Order Issue'), ('PAYMENT_ISSUE', 'Payment Issue'), ('DELIVERY_ISSUE', 'Delivery Issue'), ('PRODUCT_QUALITY', 'Product Quality'), ('REFUND', 'Refund Request'), ('OTHER', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('ESCALATED', 'Escalated')], default='OPEN', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('attachments', models.JSONField(default=list, help_text='List of attachment URLs')),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('attachments', models.JSONField(default=list)),
                ('is_staff_only', models.BooleanField(default=False, help_text='Visible only to staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MiddlemanFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('BULK_PURCHASE', 'Bulk Purchase'), ('RESELLER_PATTERN', 'Reseller Pattern'), ('MULTIPLE_ACCOUNTS', 'Multiple Accounts'), ('UNUSUAL_ORDERING', 'Unusual Ordering Pattern'), ('PRICE_GOUGING', 'Price Gouging'), ('OTHER', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('INVESTIGATING', 'Under Investigation'), ('CONFIRMED', 'Confirmed Violation'), ('FALSE_ALARM', 'False Alarm'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('description', models.TextField()),
                ('evidence_data', models.JSONField(default=dict, help_text='Structured evidence data')),
                ('supporting_docs', models.FileField(blank=True, null=True, upload_to='middleman_evidence/')),
                ('investigated_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])])),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'ico'])])),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'uploaded_at',
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='Visible to all users')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
