# Generated by Django 6.0.3 on 2026-03-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID for receiving payments (farmers only)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(default='CC0484', max_length=6),
        ),
    ]
