# Generated by Django 6.0.3 on 2026-03-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='land_photo',
            field=models.ImageField(blank=True, null=True, upload_to='land_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_photos/'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(default='0798AD', max_length=6),
        ),
    ]
