# Generated by Django 6.0.3 on 2026-03-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_land_photo_user_license_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Full address for delivery/pickup'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(default='65361F', max_length=6),
        ),
    ]
