# Generated by Django 6.0.3 on 2026-03-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_latitude_user_longitude_alter_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(default='75A8B4', max_length=6),
        ),
    ]
