# Generated by Django 6.0.3 on 2026-03-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_approved_at_product_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preorder_max_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum quantity allowed for pre‑order. Leave blank for no limit.', null=True),
        ),
    ]
