# Generated by Django 6.0.2 on 2026-03-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='accepts_cod',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='accepts_online_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='payment_info_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='payment_info_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_qr_codes/'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
