# Generated by Django 6.0.2 on 2026-03-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_farmerprofile_accepts_cod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='delivery_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='estimated_delivery_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='farm_pickup_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='free_delivery_min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='pickup_available',
            field=models.BooleanField(default=True),
        ),
    ]
