# Generated by Django 6.0.2 on 2026-03-09 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_farmerprofile_delivery_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WELCOME', 'Welcome'), ('OTP', 'OTP Verification'), ('VERIFICATION', 'Verification'), ('PROFILE', 'Profile Update'), ('ORDER', 'Order Update'), ('PAYMENT', 'Payment'), ('DELIVERY', 'Delivery'), ('PROMO', 'Promotional'), ('ALERT', 'Alert'), ('REMINDER', 'Reminder'), ('ADMIN_ALERT', 'Admin Alert'), ('SYSTEM', 'System')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_notif_user_id_c37f16_idx'), models.Index(fields=['user', 'is_read'], name='users_notif_user_id_1be17e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PROFILE_VIEW', 'Profile View'), ('PROFILE_UPDATE', 'Profile Update'), ('ORDER_VIEW', 'Order View'), ('ORDER_CREATE', 'Order Create'), ('PAYMENT', 'Payment'), ('SEARCH', 'Search'), ('EXPORT', 'Export'), ('ADMIN_ACTION', 'Admin Action')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_usera_user_id_250303_idx'), models.Index(fields=['activity_type', '-created_at'], name='users_usera_activit_257cae_idx')],
            },
        ),
    ]
