# Generated by Django 6.0.2 on 2026-03-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='delivery_partner_commission_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage of delivery fee paid to delivery partner', max_digits=5),
        ),
    ]
